---
name: "Composite action calling other workflows"
on:
  workflow_call:
  push:

jobs:

  ideology:
    name: Ideology
    uses: danny-molnar/blastarcade/.github/workflows/ideology.yml@main
  hegel:
    name: Hegel
    uses: danny-molnar/blastarcade/.github/workflows/hegel.yml@main
  generate-dependabot:
    name: Generate Dependabot
    uses: danny-molnar/blastarcade/.github/workflows/generate-dependabot.yml@main
