---
name: Testing conditional environment variables

on:
  workflow_call:
    inputs:
     IGNORE_REGEX:
        description: 'Regex string for superlinter to exclude'
        required: false
        type: string
        default: 'none'


jobs:
  test-env-vars:
    name: Test environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ inputs.IGNORE_REGEX }}
