---
name: Testing conditional environment variables

on:
  workflow_call:
    inputs:
      IGNORE_EXAMPLE_DIRECTORY:
        description: 'Flag to set to ignore example directory'
        required: false
        type: boolean
        default: false


jobs:
  test-env-vars:
    name: Test environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ inputs.IGNORE_EXAMPLE_DIRECTORY }}
