---
name: Testing conditional environment variables

on:
  workflow_call:
    inputs:
      IGNORE_EXAMPLE:
        description: 'Are we ignoring?'
        required: false
        type: boolean
        default: false
      IGNORE_REGEXP:
        description: 'What are we ignoring?'
        required: false
        type: string
        default: ''

jobs:
  test-env-vars-bool:
    name: Test environment variables - bool
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ fromJSON('["", ".*example.*"]')[inputs.IGNORE_EXAMPLE] }}

  test-env-vars-string:
    name: Test environment variables - string
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ inputs.IGNORE_REGEXP }}

  lint:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
