---
name: Testing conditional environment variables

on:
  workflow_call:
    inputs:
      IGNORE_EXAMPLE_DIRECTORY:
        description: 'Flag to set to ignore example directory'
        required: false
        type: boolean
        default: false


jobs:
  test-env-vars-if-ignore-true:
    name: Test environment variables
    if: ${{ inputs.IGNORE_EXAMPLE_DIRECTORY }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo We ignore the example directory
  test-env-vars-if-ignore-false:
    name: Test environment variables
    if: ${{ !inputs.IGNORE_EXAMPLE_DIRECTORY }}
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo We don't ignore the example directory
