---
name: Testing conditional environment variables

on:
  workflow_call:
    inputs:
     IGNORE_EXAMPLE:
        description: 'Are we ignoring?'
        required: false
        type: boolean
        default: false

env:
  VALUE: ${{ fromJSON('["none", ".*example.*"]')[!inputs.IGNORE_EXAMPLE] }}

jobs:
  test-env-vars:
    name: Test environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ env.VALUE }}
