---
name: Testing context information

on:
  workflow_call:

jobs:
  context-test:
    name: Test context information
    runs-on: ubuntu-latest
    steps:
      - name: Print event info
        run: echo ${{ toJson(github.event.repository) }}

      - name: Print workflow info
        run: echo ${{ toJson(github.event.workflow) }}
