---
name: Testing context information

on:
  workflow_call:

jobs:
  context-test:
    name: Test context information
    runs-on: ubuntu-latest
    steps:
      - name: Print if repo is template
        if: ${{ contains(github.event.repository.is_template, true) }}
        run: echo Downstream repo is template

      - name: Print if repo is not a template
        if: ${{ contains(github.event.repository.is_template, false) }}
        run: echo Downstream repo is NOT a template

      - name: Print workflow info
        run: echo ${{ fromJson(github.event.workflow) }}
        # run: echo ${{ contains(fromJson(github.event.workflow), 'context.yml') }}
