---
name: Testing context information

on:
  workflow_call:

jobs:
  context-test:
    name: Test context information
    runs-on: ubuntu-latest
    steps:
      - name: Print full GitHub Context
        run: echo ${{ toJson(github.event) }}
