---
    name: Template dependabot template

    on:
      workflow_call:
        inputs:
          LIST_OF_PACKAGES:
            description: 'List of dependency packages for template generation'
            required: false
            type: string
            default: '["terraform", "gomod"]'


    jobs:
      templatify:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Codebase
            uses: actions/checkout@v3

        #   - name: Check if Template File Exists
        #     id: check_files
        #     uses: andstor/file-existence-action@v1
        #     with:
        #       files: '.github/dependabot.template.yml'

          - name: Test
            run: echo ${{ fromJson(inputs. LIST_OF_PACKAGES) }}


        #   - name: Testing
        #     run: cat .github/dependabot.template.yml

        #   - name: Generate Dependabot Glob
        #     uses: Makeshift/generate-dependabot-glob-action@v1.2.1

        #   - name: Add and Commit
        #     uses: EndBug/add-and-commit@v9.1.2
        #     with:
        #       add: '.github/dependabot.yml'
        #       default_author: github_actions
