---
    name: Template dependabot template

    on:
      workflow_call:
        inputs:
          LIST_OF_PACKAGES:
            description: 'List of dependency packages for template generation'
            required: false
            type: string
            default: 'gomod, terraform'


    jobs:
      templatify:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Codebase
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

        #   - name: Check if Template File Exists
        #     id: check_files
        #     uses: andstor/file-existence-action@v1
        #     with:
        #       files: '.github/dependabot.template.yml'

          - name: Pythoning around
            shell: python -u {0}
            run: |
              print("Hello from the Python shell")
              variable = '${{ inputs.LIST_OF_PACKAGES }}'
              print(variable)
              print(type(variable))
              import json
              print(type(json.dumps(variable)))

        #   - name: Jinja action
        #     uses: cuchi/jinja2-action@v1.2.0
        #     with:
        #       template: .github/dependabot.template.j2
        #       output_file: .github/dependabot.output.yml
        #     #   strict: true
        #     env:
        #       packages: ${{ inputs.LIST_OF_PACKAGES }}

        #   - name: Test print
        #     run: cat dependabot.output.yml


        #   - name: Testing
        #     run: cat .github/dependabot.template.yml

        #   - name: Generate Dependabot Glob
        #     uses: Makeshift/generate-dependabot-glob-action@v1.2.1

        #   - name: Add and Commit
        #     uses: EndBug/add-and-commit@v9.1.2
        #     with:
        #       add: '.github/dependabot.yml'
        #       default_author: github_actions
