---
    name: Template dependabot template

    on:
      workflow_call:
        inputs:
          LIST_OF_PACKAGES:
            description: 'List of dependency packages for template generation'
            required: false
            type: string
            default: 'terraform, gomod'
          SCHEDULE_INTERVAL:
            description: 'Update interval frequency for template generation'
            required: false
            type: string
            default: 'daily'


    jobs:
      templatify:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Codebase
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

        #   - name: Check if Template File Exists
        #     id: check_files
        #     uses: andstor/file-existence-action@v1
        #     with:
        #       files: '.github/dependabot.template.yml'

          - name: Pythoning around
            shell: python -u {0}
            run: |
              import json, jinja2
              from jinja2 import Environment, FileSystemLoader
              print("Hello from the Python shell")
              packages_str = '${{ inputs.LIST_OF_PACKAGES }}'
              print(packages_str)
              interval_str = '${{ inputs.SCHEDULE_INTERVAL }}'
              print(interval_str)

              # create list from input
              packages_list = packages_str.split(",")

              tmpl_str = """
              ---
                version: 2
                updates:
                {% for item in list %}
                  # {% for package in item.items() %}
                  - package-ecosystem: {{item}}
                    directory: '/**/*'
                    schedule:
                      interval: {{interval}}
                  # {% endfor %}
                {% endfor %}
              """

              environment = jinja2.Environment()
              template = environment.from_string(tmpl_str)
              template.render(list=packages_list)

        #   - name: Jinja action
        #     uses: cuchi/jinja2-action@v1.2.0
        #     with:
        #       template: .github/dependabot.template.j2
        #       output_file: .github/dependabot.output.yml
        #     #   strict: true
        #     env:
        #       packages: ${{ inputs.LIST_OF_PACKAGES }}

        #   - name: Test print
        #     run: cat dependabot.output.yml


        #   - name: Testing
        #     run: cat .github/dependabot.template.yml

        #   - name: Generate Dependabot Glob
        #     uses: Makeshift/generate-dependabot-glob-action@v1.2.1

        #   - name: Add and Commit
        #     uses: EndBug/add-and-commit@v9.1.2
        #     with:
        #       add: '.github/dependabot.yml'
        #       default_author: github_actions
