---
name: Generate dependabot.yml

on:
  workflow_call:

# env:
#   TEMPLATE_FILE_CONTENTS: |
#     This is a long string
#       Many lines bla bla bla

jobs:
  generate-dependabot:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Check if Template File Exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: '.github/dependabot.template.yml'

      - name: Create Template File
        if: steps.check_files.outputs.files_exists == 'false'
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: .github/dependabot.template.yml
          contents: |
            ---
            version: 2
            updates:
              - package-ecosystem: 'terraform'
                directory: '/**/*'
                schedule:
                  interval: 'daily'

              - package-ecosystem: 'gomod'
                directory: '/**/*'
                schedule:
                  interval: 'daily'

              - package-ecosystem: 'github-actions'
                directory: '/**/*'
                schedule:
                  interval: 'daily'

      - name: Testing
        run: cat .github/dependabot.template.yml

      - name: Generate Dependabot Glob
        uses: Makeshift/generate-dependabot-glob-action@v1.2.1

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9.1.2
        with:
          add: '.github/dependabot.yml'
          default_author: github_actions
