---
name: Generate dependabot.yml

on:
  workflow_call:

env:
  TEMPLATE_FILE_NAME: 'dependabot.template.yml'
  TEMPLATE_FILE_CONTENTS: |
    This is a long string
      Many lines bla bla bla

jobs:
  generate-dependabot:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Check if Template File Exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: '.github/dependabot.template.yml'

      - name: Create Template File
        if: steps.check_files.outputs.files_exists == 'false'
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: $TEMPLATE_FILE_NAME
          FILE_DATA: $TEMPLATE_FILE_CONTENTS

      - name: Generate Dependabot Glob
        uses: Makeshift/generate-dependabot-glob-action@v1.2.1

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9.1.2
        with:
          add: '.github/dependabot.yml'
          default_author: github_actions
