---
    name: Generate dependabot.yml

    on:
      workflow_call:

    jobs:
      generate-dependabot:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Codebase
            uses: actions/checkout@v3

          - name: Generate Dependabot Glob
            uses: Makeshift/generate-dependabot-glob-action@v1.2.1
            with:
              template-file: '${{ github.workspace }}/.github/dependabot.template.yml'


          - name: Add and Commit
            uses: EndBug/add-and-commit@v9.1.2
            with:
              add: '.github/dependabot.yml'
              default_author: github_actions
