---
name: Generate dependabot.yml

on:
  workflow_call:

# env:
#   TEMPLATE_FILE_NAME: 'dependabot.template.yml'
#   TEMPLATE_FILE_CONTENTS: |
#     This is a long string
#       Many lines bla bla bla

jobs:
  generate-dependabot:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v3

      # - name: Check if Template File Exists
      #   id: check_files
      #   uses: andstor/file-existence-action@v1
      #   with:
      #     files: '.github/dependabot.template.yml'

      # - name: Create Template File
      #   uses: 'finnp/create-file-action@master'
      #   if: steps.check_files.outputs.files_exists == 'false'
      #   env:
      #     FILE_NAME: '.github/dependabot.template.yml'
      #     FILE_DATA: 'this text goes into the file'

      # - name: Testing
      #   run: |
      #     ls -laR
      #     cat .github/dependabot.template.yml

      - name: Get path
        id: get-path
        uses: michmich112/get-actions-dir-path@main
      - name: Display result
        run: |
          echo "path -> $DIRPATH"
        env:
          DIRPATH: ${{ steps.get-path.outputs.dir-path }}


      # - name: Generate Dependabot Glob
      #   uses: Makeshift/generate-dependabot-glob-action@v1.2.1
      #   with:
      #     template-file: '${{ github.action_path }}/.github/dependabot.template.yml'
      #     follow-symbolic-links: true

      # - name: Add and Commit
      #   uses: EndBug/add-and-commit@v9.1.2
      #   with:
      #     add: '.github/dependabot.yml'
      #     default_author: github_actions
