---
name: Successful Action steps test

on:
  workflow_call:

jobs:
  test-step-sequence-logic:
    runs-on: ubuntu-latest
    steps:
      - name: Print 1st text
        id: print-1
        run: |
          echo "First text printed"
          date "+%T"

      - name: Sleep 30s
        id: sleep
        run: sleep 30s

      - name: Print nonsleep text
        id: print-nonsleep
        run: |
          echo "Nonsleep text printed"
          date "+%T"

      - name: Print sleep text
        id: print-sleep
        run: |
          echo "Sleep text printed"
          date "+%T"
        if: steps.sleep.outcome == 'success'
